name: flutter_get_app_group_directory
description: "A Flutter plugin for iOS and macOS that resolves the shared container directory for an App Group."
version: 1.0.0
repository: https://github.com/MyLittleSuite/flutter_get_app_group_directory
issue_tracker: https://github.com/MyLittleSuite/flutter_get_app_group_directory/issues
homepage: https://www.mylittlesuite.com

environment:
  sdk: ">=3.0.0"

platforms:
  ios:
  macos:

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterGetAppGroupDirectoryPlugin
      macos:
        pluginClass: FlutterGetAppGroupDirectoryPlugin
