name: Build Artifacts

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup Flutter
        uses: ./.github/actions/setup
      - name: Build iOS
        if: ${{ inputs.platform == 'ios' }}
        working-directory: example/ios
        run: |
          flutter build ios --release --no-codesign
      - name: Build macOS
        if: ${{ inputs.platform == 'macos' }}
        working-directory: example/macos
        run: |
          flutter build macos --release